---
title: "Interesting and resourceful Websites for R Programming and Machine Learning"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
h1{
  text-align: center;
  color: blue;
  font-weight: bold;
}
```

# Useful Websites for Learning R 

There are many useful and interesting website for learning **R programming**. Here I am listing some of these websites 

## Official R website CRAN

This is the official R website, and it is important to bookmark this website, because it regularly publishes anouncements, publication, links to books; even more, it is the first place for learning the pure R programming Language. 

[Comprehensive R Archive Network](https://cran.r-project.org/) 

## Rstudio

Rstudio is a user-friendly Integrating Development Environment **IDE** for R. [Rstudio](https://www.rstudio.com/)

## R packages

Learning about the R packages online through the Datacamp servers. 

[R packages Documentation](https://rdocumentation.org/)

* The new added packages can be found in the next website

[New Added pachages with CRANberries](http://dirk.eddelbuettel.com/cranberries/cran/new/) 

* The Alphabetical Order Available CRAN Packages

[R Packages By Names](https://cran.r-project.org/web/packages/available_packages_by_name.html)

## Statistical Sources

### Source One

[Statmethods Website](https://www.statmethods.net/) 

### Source Two

[programming with R](https://www.programmingr.com/) 

### Source Three

[CRAN Task View: Web Technologies and Services](https://cran.r-project.org/web/views/WebTechnologies.html) 

### Source Four

[hdf5 group website](https://www.hdfgroup.org/) 

### Source Five

[stackexchange](https://stats.stackexchange.com/) 


## Journals

### Source One

[The R journal](https://journal.r-project.org/) 

### Source Two

[Journal of Statistical Software](https://www.jstatsoft.org/index) 

## Blogs

[R blogger](https://www.r-bloggers.com/) 

# Datasets & Machine Learning Competitions

### Machine Learning Repository

The University of California Irvine Repository for classification and regression datasets for practicing machine learning skills. 

[Machine Learning Repository](http://archive.ics.uci.edu/ml/index.php) 

### Open Data Portal

[Open Data Portal](https://data.ca.gov/dataset?groups=economy-and-demographics)

### kdnuggets

This is a resourceful website, it contains a variety of sources of data, courses, and many other useful information. 

[kdnuggets](https://www.kdnuggets.com/datasets/index.html)


### Kaggle

[Kaggle Competition](https://www.kaggle.com/) 

### Tune Edit

[TuneEdit competition](http://tunedit.org)
